config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'

  resources :web_crawl, only: [:index, :new] do
    collection do
      post :crawl
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end
end

app/controllers/web_crawl_controller.rb
class WebCrawlController < ApplicationController

  def new; end

  def index
    @twitter_profile = params.except('controller', 'action').as_json
  end

  def crawl
    response = TwitterCrawlService.new(crawl_params).crawling
    redirect_to web_crawl_index_path(response.as_json)
  end

  private
    def crawl_params
      params.permit(:twitter_url, :api_token)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/web_crawl_helper.rb
module WebCrawlHelper
end

app/views/home/index.html.erb
<div class="card text-center">
  <div class="card-header">
    Proxy Crawl application
  </div>
  <div class="card-body">
    <h5 class="card-title">Crawl Twitter</h5>
    <p class="card-text">This application will crawl the twitter profiles and save the profile data using proxy crawler.</p>
    <%= link_to "Crawl", new_web_crawl_path, class: 'btn btn-primary'%>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
  <%= link_to "Proxy Crawler", root_path, class: 'navbar-brand'%>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProxyCrawler</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation'%>
    <main role="main" class="container">
      <div class="main-layout mt-20">
        <%= yield %>
      </div>
    </main>
  </body>
</html>

app/views/web_crawl/index.html.erb
<div class="card text-center">
  <div class='card-header'>
    <h2> <%= @twitter_profile["name"] %> </h2>
  </div>
  <div class='card-body'>
    <% @twitter_profile.each do |key, value| %>
      <div class='row'>
        <div class='col-2'>
          <strong> <%= key %> </strong>
        </div>
        <div class='col-10'>
          <%= value %>
        </div>
      </div>
    <% end %>
  </div>
  <div class='card-footer'>
    <div class='row'>
      <div class='col-12'>
        <%= link_to 'Home', root_path, class: 'btn btn-outline-primary mr-3' %>
        <%= link_to 'Back', :back, class: 'btn btn-outline-dark' %>
      </div>
    </div>
  </div>
</div>

app/views/web_crawl/new.html.erb
<div class="card">
  <div class='card-header'>
    Crawl Twitter Profile
  </div>
  <div class='card-body'>
    <%= form_tag(crawl_web_crawl_index_path, method: :post) do %>
      <div class='form-group row'>
        <div class='col-md-6'>
          <%= label_tag :twitter_url, 'Twitter URL', class: 'font-weight-bold' %>
          <%= text_field_tag :twitter_url, '', class: 'form-control', required: true %>
        </div>
      </div>

      <div class='form-group row'>
        <div class='col-md-6'>
          <%= label_tag :api_token, 'API Token', class: 'font-weight-bold' %>
          <%= text_field_tag :api_token, '', class: 'form-control', required: true %>
        </div>
      </div>

      <div class='actions'>
        <%= submit_tag "Submit" %>
      </div>
    <% end %>
  </div>

</div>